<?php
/** Terms of use. */

require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/illustrations.php';

$siteName = site_name($pdo);
$email    = get_setting($pdo, 'contact_email', '');

$pageTitle       = 'Terms';
$pageDescription = 'The terms that apply to using this website.';
$bannerEyebrow   = 'Terms of use';
$bannerTitle     = 'Using this website';
$bannerLede      = 'Plain terms for a small charity website. Nothing here takes away a right you have by law.';
$breadcrumbs     = [['label' => 'Terms']];

require __DIR__ . '/includes/header.php';
?>

<section class="section section-cream">
  <div class="container-narrow">

    <p class="text-muted"><strong>Last updated:</strong> <?= e(date('F Y')) ?></p>

    <h2 class="h-lg">Who we are</h2>
    <p><?= e($siteName) ?> is a non-governmental organisation working in Nigeria on child literacy,
      community health, youth skills and food relief. <?= e(get_setting($pdo, 'footer_note', '')) ?></p>

    <h2 class="h-lg">Registering as a volunteer</h2>
    <p>Registering tells us you are interested. It is not a contract of employment, it does not commit
      you to attend anything, and it does not oblige us to place you. Placement depends on where you
      are, what is running near you and completion of our safeguarding briefing.</p>
    <p>Volunteers must be 16 or older. Volunteers under 18 need a parent or guardian's consent before
      attending an outreach.</p>

    <h2 class="h-lg">Giving</h2>
    <p>Giving is by bank transfer, using the details on our Support page. This website never processes
      payments and never asks for card or account details. If any page, email or phone call claiming to
      be from us asks you for those, it is not us — please tell us immediately.</p>
    <p>Gifts are used for the programmes described on this site. Where a gift is given for a specific
      programme, we apply it to that programme. We publish a funds-use summary every quarter.</p>

    <h2 class="h-lg">What you send us</h2>
    <p>If you submit a story, you confirm it is your own and you are happy for us to publish it, with
      your first name and role, on this website. We may shorten it or correct spelling, but we will not
      change its meaning. Tell us in the submission if you would rather appear anonymously, and ask us
      any time to take it down.</p>
    <p>Please do not send us anything unlawful, abusive, or that identifies a child without their
      guardian's consent. We remove such submissions without notice.</p>

    <h2 class="h-lg">Photographs on this site</h2>
    <p>We photograph our work with permission, and never a child without a guardian present and
      consenting. If you appear in a photograph here and want it removed, email us and we will take it
      down — no explanation needed.</p>
    <p>Where a photograph has not yet been supplied, this site shows an illustration generated by the
      site itself. Those are drawings, not photographs of real people.</p>

    <h2 class="h-lg">Accuracy</h2>
    <p>We keep the figures, dates and programme descriptions on this site as accurate as we can, and we
      correct mistakes when we find them. Event details can change at short notice — if you are
      travelling to one, check with us first.</p>

    <h2 class="h-lg">Using our material</h2>
    <p>The text, photographs and illustrations on this site belong to <?= e($siteName) ?>. You are
      welcome to quote or share them to tell others about the work, with attribution. Please ask before
      using anything commercially.</p>

    <h2 class="h-lg">Availability</h2>
    <p>We run this website on a best-effort basis. It may be unavailable during maintenance or for
      reasons outside our control, and we do not promise uninterrupted access.</p>

    <h2 class="h-lg">Questions</h2>
    <p>Email <?php if ($email): ?><a href="mailto:<?= e($email) ?>"><?= e($email) ?></a><?php else: ?>our office<?php endif; ?>
      and a person will answer within two working days.</p>

    <div class="btn-row u-mt-lg">
      <a class="btn btn-ghost" href="<?= e(base_url('privacy.php')) ?>">Read the privacy notice</a>
      <a class="btn btn-primary" href="<?= e(base_url('contact.php')) ?>">Contact us <?= icon('arrow') ?></a>
    </div>

  </div>
</section>

<?php require __DIR__ . '/includes/footer.php'; ?>
